= Шаблоны в C++. Часть 2
:source-highlighter: highlightjs
:icons: font

smart pointers, scoped ptr, shared ptr, RAII

== RAII

Получение ресурса есть инициализация (англ. Resource Acquisition Is Initialization (RAII)) — программная идиома объектно-ориентированного программирования, смысл которой заключается в том, что с помощью тех или иных программных механизмов получение некоторого ресурса неразрывно совмещается с инициализацией, а освобождение — с уничтожением объекта.


////
=== Управление ресурсами

.Чтение из файла в Python
[source,python]
----
with open("text.txt") as file:
    # файл открыт для чтения
    for line in file:
        print(line)

# здесь ресурс (файл) закрыт
----

ifdef::backend-revealjs[=== !]

.Чтение из файла в Java
[source,java]
----
try (var reader = new BufferedReader(
        new FileReader("text.txt"))) {
    // файл открыт для чтения
    return reader.readLine();
}
// файл закрыт
----

ifdef::backend-revealjs[=== !]

.Чтение из файла в C++
[source,cpp]
----
{
    std::fstream file {"text.txt"};

    // если выполнение дошло до этой строки,
    // значит, мы открыли файл
    std::string line;
    std::getline(file, line);
} // здесь вызовется деструктор file,
// файл будет закрыт
----

`std::fstream` соответствует идиоме RAII.
////

== Управление временем жизни

Предлагается написать “умные” указатели, которые при инициализации получают ресурс (объект выделенный в куче), а при уничтожении - освобождают ресурс.

=== Мотивация

Рассмотрим типичный код, создающий что-то на хипе:

[source,cpp]
----
lazy_string concat(lazy_string lhs, lazy_string rhs) {
    char* buffer = new char*[lhs.size() + rhs.size() + 1]{};
    for (size_t i = 0; i < lhs.size(); ++i) {
        buffer[i] = lhs.at(i);
    }
    for (size_t i = 0; i < lhs.size(); ++i) {
        buffer[lhs.size() + i] = rhs.at(i);
    }
    auto result = lazy_string(buffer);
    delete[] buffer;
    return result;
}
----

Есть ли проблемы в этом коде?

ifdef::backend-revealjs[=== !]

Мы допустили ошибку в коде, и за это платим утечкой памяти.

[source,cpp]
----
lazy_string concat(lazy_string lhs, lazy_string rhs) {
    // этот buffer утечет, если кто-то бросит исключение
    char* buffer = new char*[lhs.size() + rhs.size() + 1]{};

    for (size_t i = 0; i < lhs.size(); ++i) {
        buffer[i] = lhs.at(i);
    }
    // не по тому итерируемся, at бросит исключение
    for (size_t i = 0; i < lhs.size(); ++i) {
        buffer[lhs.size() + i] = rhs.at(i);
    }
    auto result = lazy_string(buffer);
    delete[] buffer;
    return result;
}
----

Как такая ошибка решается?

ifdef::backend-revealjs[=== !]

Можно использовать `shared_buffer`!

[source,cpp]
----
lazy_string concat(lazy_string lhs, lazy_string rhs) {
    // если кто-то кинет исключение,
    // деструктор buffer очистит память
    shared_buffer buffer{lhs.size() + rhs.size() + 1};

    for (size_t i = 0; i < lhs.size(); ++i) {
        buffer.data[i] = lhs.at(i);
    }
    for (size_t i = 0; i < rhs.size(); ++i) {
        buffer.data[lhs.size() + i] = rhs.at(i);
    }
    return lazy_string(buffer);
}
----

ifdef::backend-revealjs[=== !]

Если будет брошено исключение, то произойдет "раскрутка стека" (stack unwinding).

В процессе раскрутки будут вызваны деструкторы всех локальных переменных.

Т.е. будет вызван деструктор shared_buffer => утечки не будет.

ifdef::backend-revealjs[=== !]

Вы уже пользуетесь RAII:

* `std::string` для `char const*`
* `std::vector` и другие контейнеры для `T[]`
* `std::fstream` для `FILE*` (условно)

Это RAII-обертки для часто используемых ресурсов.

Но когда у вас много своих типов, писать для каждого обертку не хочется.

ifdef::backend-revealjs[=== !]

Хочется иметь инструмент, который можно использовать в сочетании с произвольным указателем
и уберечь себя от утечек.

Наличие в C++ классов, конструкторов/деструкторов, шаблонов и перегрузки операторов позволяет создать такой инструмент:

*Умные указатели*

== Задача 1. scoped_ptr<T>

0.5 балла.

Время жизни такого указателя - от места создания указателя до конца объемлющего скоупа.

ifdef::backend-revealjs[=== !]

[source,cpp]
----
void bar() {
    scoped_ptr<foo> foo_ptr(new foo {0, 111});
    std::cout << (*foo_ptr).field1
        << foo_ptr->field1
        << foo_ptr.get()
        << std::endl;

    if (foo_ptr) foo_ptr->field1 += 1;

    foo_ptr = std::move(foo_ptr); // - compilation fails
    auto foo_ptr2(foo_ptr);// - compilation fails
    foo_ptr = foo_ptr; // - compilation fails
    bool status = foo_ptr; // - compilation fails
} // foo_ptr destroys. Operator delete is called.
----

ifdef::backend-revealjs[=== !]

[source,cpp]
----
foo_ptr.reset(); //now foo_ptr->field1 fails in runtime
foo_ptr.reset(new foo {0, 111}); //now ok
foo* ptr = foo_ptr.release(); //foo_ptr->field1 - fails
scoped_ptr<foo> foo_ptr2; //foo_ptr2->field1 fails in runtime

// provide useful types
decltype(foo_ptr)::element_type foo_on_stack { 999, 1000 };
----

ifdef::backend-revealjs[=== !]

WARNING: Это задание стоит сделать на паре.

////
== Задача 2. unique_ptr<T>

1 балл

Это расширение `scoped_ptr`, которое поддерживает передачу владения ресурсом другому `unique_ptr` при операции `move` и при возврате из функции.

ifdef::backend-revealjs[=== !]

[source,cpp]
----
unique_ptr<foo> foo_uptr(new foo {666, 777});
unique_ptr<foo>  foo_uptr2 = std::move(foo_uptr); // - ok
foo_uptr2 = std::move(foo_uptr2); // - ok
std::cerr << foo_uptr->field1 << std::endl; // - runtime fail
unique_ptr<foo> foo_uptr3(foo_uptr); // - compilation fails
----

ifdef::backend-revealjs[=== !]

[source,cpp]
----
unique_ptr<foo> create_foo() {
    return unique_ptr<foo>(new foo {666, 777}); // move ctor
}
unique_ptr<foo> foo_ptr = create_foo(); // move assign

void receive_foo(unique_ptr<foo> foo_ptr) {
...
}
receive_foo(create_foo()); // move ctor
----
////

== Задача 2. shared_ptr<T>

1 балл.

Это более умный указатель, которое поддерживает копирование и удаляет ресурс после удаления последнего ссылающегося умного указателя. Должен обладать следующими функциями:

[source,cpp]
----
// возвращает хранимый указатель
T* get() const;
// заменяет хранимый указатель на другой
void reset(T* other = nullptr);
// а также явный оператор приведения к bool.
// Возвращает true, если указатель непустой
----

ifdef::backend-revealjs[=== !]

[source,cpp]
----
shared_ptr<foo> foo_shptr(new foo {888, 999});
shared_ptr<foo> foo_shptr2 = foo_shptr;
assert(foo_shptr.get() == foo_shptr2.get());
std::cout << foo_shptr->field1
    << " "
    << foo_shptr2->field1
    << std::endl;

// bad usage
// leads to double delete
shared_ptr<foo> foo_shptr3(foo_shptr2.get());
----

== Задача 3. weak_ptr<T>

1 балл.

Этот указатель является дополнением `shared_ptr`, и служит для решения проблемы циклических ссылок.
Должен обладать следующими операциями:

[source,cpp]
----
// очищает хранимый указатель (присваивает в него nullptr)
void reset();

// возвращает true, если объект уже удалён
bool expired() const;

// возвращает сильный указатель, если он ещё не был удален
// иначе пустой shared_ptr
shared_ptr<T> lock() const;
----

=== Зачем нужен lock?

Допустим, `weak_ptr` имеет интерфейс как у `shared_ptr`.

[source,cpp]
----
void do_something(weak_ptr<user> ptr) {
    if (!ptr.expired()) {
        auto name = ptr->name;
    }
}
----

Что может пойти не так?

ifdef::backend-revealjs[=== !]

Проблема: можно обратиться к уже удаленному объекту.

[source,cpp]
----
void do_something(weak_ptr<user> ptr) {
    // тут объект существует
    if (!ptr.expired()) {
        // в это время последний shared_ptr был удален
        //
        // обращение к удаленному объекту
        auto name = ptr->name;
    }
}
----

Нам нужно получить "сильную ссылку" на объект.

ifdef::backend-revealjs[=== !]

`lock` должен вернуть `shared_ptr`, который не даст объекту преждевременно погибнуть.

[source,cpp]
----
void do_something(weak_ptr<user> ptr) {
    if (!ptr.expired()) {
        auto strong_ptr = ptr.lock();
        auto name = strong_ptr->name;
    }
}
----

Теперь всё хорошо?

ifdef::backend-revealjs[=== !]

Проблема: можно не успеть создать `shared_ptr`.

[source,cpp]
----
void do_something(weak_ptr<user> ptr) {
    // тут объект существует
    if (!ptr.expired()) {
        // здесь он погиб
        // поэтому strong_ptr пуст
        auto strong_ptr = ptr.lock();
        // обращение по nullptr
        auto name = strong_ptr->name;
    }
}
----

Что делать?

ifdef::backend-revealjs[=== !]

Решение: нужно проверить `strong_ptr` перед использованием.

[source,cpp]
----
void do_something(weak_ptr<user> ptr) {
    auto strong_ptr = ptr.lock();
    if (strong_ptr) {
        auto name = strong_ptr->name;
    }
    // здесь strong_ptr уже не нужен
}
----

ifdef::backend-revealjs[=== !]

Можно ещё лучше!

[source,cpp]
----
void do_something(weak_ptr<user> ptr) {
    // объявление и инициализация прямо в if
    if (auto strong_ptr = ptr.lock()) {
        auto name = strong_ptr->name;
    }
    // здесь strong_ptr уже не доступен
}
----

=== Пример использования weak_ptr
[source,cpp]
----
weak_ptr<foo> weak_foo; // empty
shared_ptr<foo> strong_foo(new foo {1, 2});
weak_foo = strong_foo;

if (shared_ptr<foo> lock = weak_foo.lock()) {
    assert(lock->field1 == 1);
}

strong_foo.reset();
assert(weak_foo.expired());
----