= Семинар №4: Встроенные типы, инструкции и операторы
:revealjs_theme: white

== Типичные ошибки прошлого семинара

=== Бессмысленный const

[source,cpp]
----
int** create_matrix(...) {...}
----

Здесь явно не хватает `const`-ов.

ifdef::backend-revealjs[=== !]

[source,cpp]
----
int* const* const create_matrix(...) {...}
----

Зачем нужен каждый из `const`-ов?

ifdef::backend-revealjs[=== !]

[source, cpp]
----
int* const* arr = create_matrix(...);
arr = nullptr; // const не помог
----

Возврат происходит по значению, `const` не имеет смысла.

=== Недостающий const

[source,cpp]
----
void release_matrix(int* const* matrix) { ... }
----

Эта сигнатура стесняет пользователя.

ifdef::backend-revealjs[=== !]

[source,cpp]
----
int const* const* id_matrix = ctreate_id_matrix(64);
...
release_matrix(id_matrix); // ошибка компиляции
----

ifdef::backend-revealjs[=== !]

Правильная сигнатура:

[source,cpp]
----
void release_matrix(int const* const* matrix) { ... }
----

=== Variable length arrays

[source,cpp]
----
void foo(size_t size) {
    int array[size] {};
    ...
}
----

Q: Все ли в порядке с этим кодом?

ifdef::backend-revealjs[=== !]

A: Такой код запрещен стандартом C++.

В качестве размера статического массива можно использовать
только константы времени компиляции.

=== Работа с беззнаковыми типами

[source,cpp]
----
void sort(int* arr, size_t size) {
    for (int i = 0; i < size - 1; i++) {
        for (int j = i + 1; j < size; j++) {
            ...
        }
    }
}
----

Сколько в этом коде проблем?

ifdef::backend-revealjs[=== !]

Исправленный код:

[source,cpp]
----
void sort(int* arr, size_t size) {
    for (size_t i = 0; i < size; ++i) {
        for (size_t j = i + 1; j < size; ++j) {
            ...
        }
    }
}
----

== Задачи семинара

* Понять различия между разными видами cast’ов и правильно выбирать нужный.
* Разработать систему ботов, умеющих считать и воровать.

== Задачи

В серии заданий мы будем создавать бота, умеющего выполнять различные команды пользователя.

ifdef::backend-revealjs[=== !]

Интерфейс бота описывается следующим образом:

[source,cpp]
----
struct bot_state; // реализация на ваше усмотрение

struct bot_environment {
    std::istream* in;
    std::ostream* out;
    std::ostream* err;
};
----

[source,cpp]
----
bot_state* init_bot();

void execute_command(bot_environment const* env, bot_state* state, char const* command);

void stop_bot(bot_state const* state);
----

ifdef::backend-revealjs[=== !]

Для общения с окружающим миром используется класс `bot_environment`.

Информацию об ошибочных ситуациях бот должен выводить в `err`, результат выполненной команды -- в `out`.

ifdef::backend-revealjs[=== !]

Если бот получает неизвестную ему команду, он должен напечатать `Unknown command '<command>'!\n` в `err`,
где `<command>` -- это необработанная команда.

Если бот получает некорректные данные в `execute_command` (например, `nullptr`), он
должен бросить исключение `std::runtime_error`.

=== Задача №1: Hello from bot (1 балл)

Научим бота приветствовать пользователя!

Бот должен уметь обрабатывать команду `h`, в ответ на которую он должен выводить `Hello!\n` в `out`.

=== Задача №2: Арифметика

Научите бота складывать целые числа и числа с плавающей запятой.

Бот должен хранить в своем состоянии цепочку чисел (не более 16), которые ему передает пользователь.

Если кончился лимит чисел, то при очередной команде бот печатает `Cannot add more numbers!\n`.

ifdef::backend-revealjs[=== !]

Команда вида `a <number>` (например, `a 10`) добавляет в эту цепочку целое число `<number>` (`unsigned long`).

Команда вида `f <number>` (например, `f 10.1`) добавляет в эту число `<number>` (`float`).

ifdef::backend-revealjs[=== !]

Команда `r` выводит в `out` строку вида `<expression> = <result>`, где `<expression>` -- выражение-сумма
сохраненной цепочки чисел, а `<result>` -- результат вычисления этого выражения.

После этого цепочка сохраненных чисел очищается.

Если до этого не было не одной команды, то бот печатает `Nothing to compute!\n`.

ifdef::backend-revealjs[=== !]

Пример последовательности команд:

----
> a 10
> a 20
> f 10.1
> r
10 + 20 + 10.1000 = 30
----

При вычислении суммы все числа с плавающей запятой должны быть явно приведены к `unsigned long`.

Числа с плавающей точкой печатать с 4 знаками после запятой.

=== Задача №3: "Я хочу воровать"

Мы хотим научить бота воровать данные у конкурентов.

Реализуйте команду `s <address>` (например, `s 0x5631c2ace023`),
результатом которой является то, что бот находит bot_state,
лежащий по этому адресу, забирает у бота последнее число, которое
ему добавили, и добавляет его себе.

ifdef::backend-revealjs[=== !]

Если у бота-вора нет места под новые числа, то он должен напечатать в `err` `Cannot add more numbers!\n`.

Если у обкрадываемого бота нет чисел, то бот-вор должен напечатать в `err` `Have nothing to steal!\n`.
