= Семинар №5: Функции
:revealjs_theme: white
:revealjs_mouseWheel: true
:icons: font

== Типичные ошибки прошлого семинара

== Задачи семинара

* Познакомиться с базовыми контейнерами.
* Вспомнить, как можно передавать/возвращать значения в функции.
* Закрепить передачу функций по указателю.
* Поиграть с анонимными функциями.

== Типы-контейнеры

Мы часто использовали массивы и `С`-style строки.

В `C++` есть более удобные их альтернативы:

* `std::vector<T>` -- саморасширяющийся массив произвольного типа.
* `std::string` -- строка, знающая свой размер.

=== Создание вектора

[source,cpp]
----
vector<int> empty_vec;
vector<int> another {};

vector<double> with_values {1, 2, 3.4};

vector<double> copy(with_values);
vector<double> another_copy = copy;
----

=== Вставка/удаление из вектора

[source,cpp]
----
vec.size(); // => 0;

vec.push_back(10);
vec.push_back(20);

vec.back(); // => 20
vec.front(); // => 10
vec[0] = 30;
vec[0]; // 30
vec[1]; // 10

vec.pop_back();
vec.size(); // => 1;
----

=== Итерация по вектору

[source,cpp]
----
vector<int> vec { 1, 2, 3 };
// если по какой-то причине нужен индекс
for (size_t i = 0; i < vec.size(); ++i) {
    int& elem = vec[i];
}

// если не нужен индекс
for (auto it = vec.begin(); it != vec.end(); ++it) {
    int& elem = *it;
}

// C++11 и выше
for (auto& elem: vec) {
    ...
}
----

=== Создание строки

[source,cpp]
----
string empty;
string another_empty{};

string hello {"hello"};
string another_hello = "hello";
string third_hello("hello");
----

У строки есть много удобных методов:

* `substring`
* `find`
* `c_str`
* ...

ifdef::backend-revealjs[=== !]

Q: Что написано на последней строчке?

----
string empty;

string another_empty{};

string completely_empty();
----

[.step]
* A: Это объявление функции `string completely_empty()`.

=== Итерация по строке

Так же, как и по вектору.

== CPP Reference

Очень полезный сайт с информацией про `C++`.

Хотите взять подстроку у строки?

* Ищите в гугле `cpp reference string`
* http://www.cplusplus.com/reference/string/string/
* Смотрите методы, находите `substr`
* PROFIT

== Передача значений в функции

////
Итак, вам на лекции объясняли, что есть два способа передачи и возврата чего-либо в функции. Какие?

Правильно:

* по ссылке.
* по значению.
////

Какие есть способы передать что-либо в функцию?

[.step]
* По ссылке.
* По значению.

ifdef::backend-revealjs[=== !]
Что значит "передать что-то по ссылке"?

[source,cpp]
----
void foo(int& i) { /* body */ }

int j = /**/;

foo(j);
----


////
Что значит передать что-то по ссылке? В каком-то смысле это синтаксический сахар над передачей по константному указателю.

Отличие в том, что, в отличие от указателя, ссылку нельзя переприсвоить (т.е. заставить указывать на другой участок памяти).
////

ifdef::backend-revealjs[=== !]

Передача по ссылке -- синтаксический сахар.

Такой код:
[source,cpp]
----
void foo(int& i_ref) {
    ref += 10;
}
----

эквивалентен такому:

----
void foo(int* const i_ptr) {
    *i_ptr += 10;
}
----

ifdef::backend-revealjs[=== !]

////
Что значит передать в функцию по значению?

Это значит сконструировать копию при вызове, передать эту копию в функцию, и уничтожить по окончании вызова.

Что значит сконструировать, что значит копию и что значит уничтожить?

Сконструировать - значит выделить память на стеке (именно на стеке, потому что мы говорим о передаче параметров в функцию) и как-то её проинициализировать. Очевидно, что это не выделение в смысле выделения динамической памяти, т.е. оверхед на само это выделение скорее всего отсутствует, т.к. предподсчитан заранее.

Копия означает, что мы конструируем объект по подобию другого объекта такого же типа. Это очевидная операция для примитивов и для POD-структур (нужно просто скопировать содержимое памяти).

Уничтожить - значит освободить занимаемые объектом ресурсы. В случае примитивов и подов все так же очевидно.
////

Что значит "передать что-то по значению"?

[source,cpp]
----
void foo(int i) { /* body */ }

int j = /**/;

foo(j);
----

[.step]
* Сконструировать объект-копию при вызове.
* Передать эту копию в функцию.
* Уничтожить по окончании вызова.

ifdef::backend-revealjs[=== !]

Рассмотрим функцию `sum`.

[source,cpp]
----
double sum(std::vector<doulbe> vec) {
    double result = 0;
    for (double d : vec) {
        result += d;
    }
}
----

Q: Что здесь не так?

ifdef::backend-revealjs[=== !]

A: Вектор передается по значению, а значит он будет целиком скопирован. В этом нет нужды.

Вот так лучше:

[source,cpp]
----
double sum(std::vector<doulbe> const& vec) {
    double result = 0;
    for (double d : vec) {
        result += d;
    }
}
----

ifdef::backend-revealjs[=== !]

WARNING: Если объект произвольного размера (контейнер) можно не копировать, не нужно этого делать.

----
void print_all(std::vector<std::string> vec) {
    for (size_t i = 0; i < vec.size(); ++i) {
        std::string current = vec[i]; // лишняя копия
        std::cout << current << std::endl;
    }
}
----

== Лямбда-функции и указатели на функции

Мы не будем вдаваться в детали работы с лямбда-функциями.

Однако их можно использовать как замену функциям, объявленным только ради
их передачи куда-либо.

ifdef::backend-revealjs[=== !]

[source, cpp]
----
double string_to_double(std::string const& s) {...};
...
std::vector<std::string> vec { "Hello", "world" };
sum(vec, string_to_double);
----

Ради каждого использования объявлять новую функцию-трансформер -- неудобно.

ifdef::backend-revealjs[=== !]

Воспользуемся лямбда-функцией, чтобы этого избежать.

[source, cpp]
----
std::vector<std::string> vec { "Hello", "world" };
sum(vec, [](std::string const& s) -> double {...});
----

Как это работает?

ifdef::backend-revealjs[=== !]

Синтаксис лямбда-функции создает объект определенного, но безымянного типа.

Если лямбда не захватила внутрь никаких переменных, то у этого типа будет определена
конверсия к соответствующему типу-указателю на функцию.

ifdef::backend-revealjs[=== !]

Так можно:
[source, cpp]
----
auto obj = [](std::string const& s) -> double { ... };
double(*ptr)(std::string const& s) =
    static_cast<double(*)(std::string const& s)>(obj);
----

А так уже нельзя:
----
double x = 10;
auto obj = [&x](std::string const& s) -> double { return x++; };
// это не сработает
double(*ptr)(std::string const& s) =
    static_cast<double(*)(std::string const& s)>(obj);
----


////
В отличие от C, C++ позволяет нам контролировать то, как объект создается, копируется и уничтожается.
За счет этого можно создавать типы, которые
////

== Задачи

Если вы знакомы с `std::algorithms`, то его нельзя использовать при выполнении этих задач.

=== Задача №1

Напишите функцию `for_each`, принимающую `vector<int>` и указатель на функцию, принимающую `int` и возвращающую `void`.

Функция должна последовательно выполнить переданную функцию на каждом из элементов вектора.

Возвращаемый тип функции -- `void`.

=== Задача №2

Напишите несколько функций для чтения/записи типизированных данных из/в массив памяти.

----
char* read(char* input, int& i);
char* write(char* input, int i);

char* read(char* input, size_t& i);
char* write(char* input, size_t i);

char* read(char* input, char*);
char* write(char* input, char const*);
----

Возвращаемое значение -- указатель на участок памяти, с которого можно продолжать чтение/запись.

=== Задача №3

Напишите функцию combine, принимающую вектор и две функции -- mult и plus.

Эта функция должна вернуть значение выражения вида

----
(a1 * a2) + (a3 * a4) + a5
----

для векторов нечетной длины, и

----
(a1 * a2) + (a3 * a4) + (a5 * a6)
----

для векторов четной длины.
