= ООП: Динамический полиморфизм. Виртуальные функции.
:source-highlighter: highlightjs

== Типичные ошибки в прошлой дорешке

* Не переиспользование `+=` в `+` или наоборот.
* Игнорирование стандартных функций (`strstr`, `strcmp`) в "простой" реализации.

== Использование CMake

Если вы уже видели это на прошлом семинаре, можете пропустить эту часть.

ifdef::backend-revealjs[=== !]

Если вы решили задачу, убедитесь в том, что ваше решение можно собрать через `CMake`.

Для этого достаточно добавить/раскомментировать строчку `add_executable` в `CMakeLists.txt`.

=== Пример

В *текущей* дорешке есть два таргета, добавленных командой `add_executable`:

[source,cmake]
----
add_executable(task-1-test <компилируемые файлы>)
add_executable(task-2-test <компилируемые файлы>)
----

ifdef::backend-revealjs[=== !]

Если вы добавили свой файл `my_awesome.cpp`, и используете его во втором задании,
то модифицируйте соответствующий таргет.

[source,cmake]
----
...
add_executable(task-2-test my_awesome.cpp ...)
----


== Задачи занятия

Попрактиковаться писать полиморфные классы и использовать их

== Описание задач

Мы будем реализовывать свою библиотеку полиморфных стримов.

ifdef::backend-revealjs[=== !]

Есть базовый класс `my_ostream` с виртуальными методами. 
Есть несколько наследников `my_ostream`.
Стримы умеют выводить в поток три типа: `int`, `double`, `string`.

=== Пример кода 

[source,cpp]
----
my_ostream_con cout;                    // console output
my_ostream_file cerr("errors.txt");     // file output
my_ostream_db dbout(...);               // db output 

int main() {
  std::vector<my_ostream*> stream_ptrs = {&cout, &cerr, &dbout};
  for (auto stream_ptr : stream_ptrs)
    (*stream_ptr) << "Hello world on console!" << "\n"
                  << 1 << 2 << 3 << 4 << "\n"
                  << 777.777 <<  "\n";
  
  return 0;
}
----

== Задача №1 (1 балл)

Реализовать базовый класс `my_ostream`, одного наследника `my_ostream_con` для вывода данных в консоль.

Должен поддерживаться вывод: `int`, `double`, `std::string`.


== Задача №2 (1 балл)

Реализовать наследника `my_ostream_file`, который выводит данные в файл. Попробуйте использовать стримы полиморфно, как на слайде предисловия (положить указатели в вектор и записать что-нибудь одновременно в два стрима).

Работа с файлом должна быть корректной (файл должен быть закрыт после того, как объект `my_ostream_file` уничтожен)

== Задача №3 (1 балл)

Реализовать наследника `my_ostream_combo`, который принимает в конструкторе два стрима и комбинирует их. Т.е. при записи в такой стрим, информация записывается во оба переданных ему в конструктор стрима.

